### PR TITLE
Update CONTRIBUTORS.rst

### PR DESCRIPTION
**Pull request by jongra**
#5

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@jongra I just ran into this issue. Have you signed the contributor's agreement yet? It is quick and you can submit it by email. https://plone.org/foundation/contributors-agreement

**Comment by jensens** [comment]
This is collective. No need for a CLA here. 

Anyway I would move the references to the `*.rst` files to `setup.cfg`.

**Comment by tkimnguyen** [comment]
Hm, but there is an automated test that checks for the signed contributors agreement

**Comment by jongra** [comment]
Hello everybody,
I didn't had the time to investigate the problem in more detail, neither to read trough CLAs.
The change I pushed is a quick and dirty fix (as a reminder to myself), which I would not transfer to production. 
@jensens I think this would be a good solution. 
> Anyway I would move the references to the *.rst files to setup.cfg

By the way, this is by far not the only sub-package for plone, where the error occurs!

**Pull request closed without merging**
